/// ----------------------------------------------------------- ///
/// this file implements a test case for register tracing       ///
/// ----------------------------------------------------------- ///

#include "qtrace-client-header.h"
#include <stdio.h>

#define REG_PRINT 0

void RegSim16(uint16_t rax,
              uint16_t rcx,
              uint16_t rdx,
              uint16_t rbx,
              uint16_t rsp,
              uint16_t rbp,
              uint16_t rsi,
              uint16_t rdi,
              uint16_t r8,
              uint16_t r9,
              uint16_t r10,
              uint16_t r11,
              uint16_t r12,
              uint16_t r13,
              uint16_t r14,
              uint16_t r15,
              uint16_t rip,
              const char* fname)
{
    printf("%s: 0x%x 0x%x 0x%x 0x%x 0x%x 0x%x 0x%x 0x%x\t"
           "0x%x 0x%x 0x%x 0x%x 0x%x 0x%x 0x%x 0x%x 0x%x\n", 
            fname, rax, rcx, rdx, rbx, rsp, 
            rbp, rsi, rdi, r8,  r9, 
            r10, r11, r12, r13, r14, 
            r15, rip);
}

void RegSim32(uint32_t rax,
              uint32_t rcx,
              uint32_t rdx,
              uint32_t rbx,
              uint32_t rsp,
              uint32_t rbp,
              uint32_t rsi,
              uint32_t rdi,
              uint32_t r8,
              uint32_t r9,
              uint32_t r10,
              uint32_t r11,
              uint32_t r12,
              uint32_t r13,
              uint32_t r14,
              uint32_t r15,
              uint32_t rip,
              const char* fname)
{
    printf("%s: 0x%x 0x%x 0x%x 0x%x 0x%x 0x%x 0x%x 0x%x\t"
           "0x%x 0x%x 0x%x 0x%x 0x%x 0x%x 0x%x 0x%x 0x%x\n", 
            fname, rax, rcx, rdx, rbx, rsp, 
            rbp, rsi, rdi, r8,  r9, 
            r10, r11, r12, r13, r14, 
            r15, rip);
}


void RegSim64(uint64_t rax,
              uint64_t rcx,
              uint64_t rdx,
              uint64_t rbx,
              uint64_t rsp,
              uint64_t rbp,
              uint64_t rsi,
              uint64_t rdi,
              uint64_t r8,
              uint64_t r9,
              uint64_t r10,
              uint64_t r11,
              uint64_t r12,
              uint64_t r13,
              uint64_t r14,
              uint64_t r15,
              uint64_t rip,
              const char* fname)
{
    printf("%s: 0x%lx 0x%lx 0x%lx 0x%lx 0x%lx 0x%lx 0x%lx 0x%lx\t"
           "0x%lx 0x%lx 0x%lx 0x%lx 0x%lx 0x%lx 0x%lx 0x%lx 0x%lx\n", 
            fname, rax, rcx, rdx, rbx, rsp, 
            rbp, rsi, rdi, r8,  r9, 
            r10, r11, r12, r13, r14, 
            r15, rip);
}

static void RegSimPreInst(uint64_t rax,
                          uint64_t rcx,
                          uint64_t rdx,
                          uint64_t rbx,
                          uint64_t rsp,
                          uint64_t rbp,
                          uint64_t rsi,
                          uint64_t rdi,
                          uint64_t r8,
                          uint64_t r9,
                          uint64_t r10,
                          uint64_t r11,
                          uint64_t r12,
                          uint64_t r13,
                          uint64_t r14,
                          uint64_t r15,
                          uint64_t rip,
                          uint32_t eax,
                          uint32_t ecx,
                          uint32_t edx,
                          uint32_t ebx,
                          uint32_t esp,
                          uint32_t ebp,
                          uint32_t esi,
                          uint32_t edi,
                          uint32_t r8d,
                          uint32_t r9d,
                          uint32_t r10d,
                          uint32_t r11d,
                          uint32_t r12d,
                          uint32_t r13d,
                          uint32_t r14d,
                          uint32_t r15d,
                          uint32_t eip,
                          uint16_t ax,
                          uint16_t cx,
                          uint16_t dx,
                          uint16_t bx,
                          uint16_t sp,
                          uint16_t bp,
                          uint16_t si,
                          uint16_t di,
                          uint16_t r8w,
                          uint16_t r9w,
                          uint16_t r10w,
                          uint16_t r11w,
                          uint16_t r12w,
                          uint16_t r13w,
                          uint16_t r14w,
                          uint16_t r15w,
                          uint16_t ip)

{
#if 0
    RegSim64(rax, rcx, rdx, rbx, rsp, rbp, rsi, rdi, r8, r9, r10, r11, r12, r13, r14, r15, rip, "RegSimPreInst64");
    RegSim64(eax, ecx, edx, ebx, esp, ebp, esi, edi, r8d, r9d, r10d, r11d, r12d, r13d, r14d, r15d, eip, "RegSimPreInst32");
#endif
    RegSim16(ax, cx, dx, bx, sp, bp, si, di, r8w, r9w, r10w, r11w, r12w, r13w, r14w, r15w, ip, "RegSimPreInst16");
}

static void RegSimPstInst(uint64_t rax,
                          uint64_t rcx,
                          uint64_t rdx,
                          uint64_t rbx,
                          uint64_t rsp,
                          uint64_t rbp,
                          uint64_t rsi,
                          uint64_t rdi,
                          uint64_t r8,
                          uint64_t r9,
                          uint64_t r10,
                          uint64_t r11,
                          uint64_t r12,
                          uint64_t r13,
                          uint64_t r14,
                          uint64_t r15,
                          uint64_t rip)
{
    RegSim(rax, rcx, rdx, rbx, rsp, rbp, rsi, rdi, r8, r9, r10, r11, r12, r13, r14, r15, rip, "RegSimPstInst");
}

void InstructionCallBack(unsigned type)
{
#if 1 
    QTRACE_INSTRUCTION_INSTRUMENT(QTRACE_BEGIN_ARG,
                                  QTRACE_IPOINT_BEFORE, 
                                  QTRACE_IFUN, RegSimPreInst, 
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_RAX,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_RCX,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_RDX,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_RBX,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_RSP,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_RBP,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_RSI,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_RDI,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_R8,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_R9,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_R10,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_R11,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_R12,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_R13,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_R14,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_R15,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_RIP,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_EAX,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_ECX,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_EDX,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_EBX,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_ESP,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_EBP,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_ESI,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_EDI,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_R8D,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_R9D,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_R10D,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_R11D,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_R12D,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_R13D,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_R14D,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_R15D,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_EIP,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_AX,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_CX,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_DX,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_BX,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_SP,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_BP,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_SI,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_DI,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_R8W,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_R9W,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_R10W,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_R11W,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_R12W,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_R13W,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_R14W,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_R15W,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_IP,
                                  QTRACE_END_ARG);

#else
    QTRACE_INSTRUCTION_INSTRUMENT(QTRACE_BEGIN_ARG,
                                  QTRACE_IPOINT_AFTER, 
                                  QTRACE_IFUN, RegSimPstInst, 
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_RAX,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_RCX,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_RDX,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_RBX,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_RSP,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_RBP,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_RSI,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_RDI,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_R8,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_R9,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_R10,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_R11,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_R12,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_R13,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_R14,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_R15,
                                  QTRACE_REGTRACE_VALUE,
                                  QTRACE_X86_RIP,
                                  QTRACE_END_ARG);

#endif
    return;
}

void StatsReset() { printf("REGSIM: StatsReset\n"); }
void StatsPrint() { printf("REGSIM: StatsPrint\n"); }

static int main(void) __attribute__((constructor));
int main(void)
{
   AddInstructionCallBack(InstructionCallBack);
   AddStatsResetCallBack(StatsReset);
   AddStatsPrintCallBack(StatsPrint);
   return 0;
}
